Styling
Danieldotcomcoder/Bookstore-react-redux pull request #4
Opened 2021-12-09 18:14 UTC by Danieldotcomcoder

Added Styles to the project.
Try to match Zeplin's design.

2021-12-09 18:51 UTC, DeliceLydia requested changes
# Change Requested ♻️

## Hi @Danieldotcomcoder, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Keep Rocking!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-09 18:51 UTC, DeliceLydia commented on src/App.js
>          </nav>
- [ ] Please add an icon missing in the navbar check the design

2021-12-09 18:51 UTC, DeliceLydia commented on src/components/Book.js
> +      </div>
- [ ] I highly suggest using the same colors as in the design
- `#0290ff`
- `#e8e8e8`

- [ ] Add some margin bottom to be able to see the form properly

2021-12-10 08:14 UTC, rukundoeric approved these changes
Hi @Danieldotcomcoder,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-10 08:28 UTC, merged